###################################################################################################
# Dockerfile for db-analytics-tools Streamlit Web Application                                     #
# Created by: Joseph Konka                                                                        #
# Date: 2026-04-24                                                                                #
###################################################################################################

# Base Docker Image
FROM python:3.11-alpine

# Disable interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Set Working directory
WORKDIR /app

# Install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir --upgrade db-analytics-tools

# Enable access to the port
EXPOSE 8050

# Launch application
CMD crond -b -l 2 && db_tools start --config=config.json --address=0.0.0.0 --port=8050

###################################################################################################
#                                                                                                 #
###################################################################################################