###################################################################################################
# Dockerfile for db-analytics-tools Streamlit Web Application                                     #
# Created by: Joseph Konka                                                                        #
# Date: 2026-05-24                                                                                #
###################################################################################################

# Base Docker Image
FROM python:3.11-alpine

# Set Working directory
WORKDIR /app

# Install system dependencies for SQL Server ODBC (including bash for mssql-tools)
RUN apk add --no-cache curl gnupg eudev-dev unixodbc-dev g++ build-base bash

# Install Microsoft ODBC Driver for SQL Server
RUN curl -O https://raw.githubusercontent.com/joekakone/db-analytics-tools/refs/heads/master/install_msodbcsql.sh && \
    chmod +x install_msodbcsql.sh && \
    ./install_msodbcsql.sh && \
    rm -rf install_msodbcsql.sh

# Install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir --upgrade db-analytics-tools

# Enable access to the port
EXPOSE 8050

# Launch application (starts crond in background, then runs db_tools)
CMD crond -b -l 2 && db_tools start --config=config.json --address=0.0.0.0 --port=8050

###################################################################################################
#                                                                                                 #
###################################################################################################