########################################################################################
# docker-compose.yml for db-analytics-tools Streamlit Web Application                  #
# Created by: Joseph Konka                                                             #
# Date: 2026-05-24                                                                     #
########################################################################################

services:
  db-analytics-tools-ui:
    image: joekakone/db-analytics-tools-ui:0.2
    build:
      context: .
      dockerfile: Dockerfile.ui
    restart: always
    ports:
      - "8050:8050"
    volumes:
      - ./config.json:/app/config.json
      - db_cron_data:/var/spool/cron/crontabs
    networks:
      - db-analytics-tools-network
      # - deploy-data-warehouse_analytics-network

volumes:
  db_cron_data:
    driver: local

networks:
  db-analytics-tools-network:
    driver: bridge
  # deploy-data-warehouse_analytics-network:
  #   external: true
