name: PyPI Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: pypi-AgEIcHlwaS5vcmcCJDM0ZTZlYWFkLWY1ZDYtNGE1Ny1hN2Y5LTQwZTY2ODgyMTVmZAACGlsxLFsiZGItYW5hbHl0aWNzLXRvb2xzIl1dAAIsWzIsWyJmZWZiMWM3My03ZDlhLTQ2ODgtOGRhMS02YzA3MjY2NmUwOGIiXV0AAAYgNx1EvZvZlok14fX-ib-6K6JTeEjBUSziInDy0INPNp8
      run: |
        python -m pip install --upgrade twine
        twine upload dist/*
